import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import AlertContainer from '@/components/Alert/AlertContainer';
import ToastContainer from '@/components/Toast/ToastContainer';

import { Providers } from './providers';

const pretendard = localFont({
  src: [
    {
      path: '../../public/fonts/Pretendard-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-pretendard',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${pretendard.variable} antialiased`}>
        <Providers>{children}</Providers>

        <div id='toast-container' />
        <div id='alert-root' />
        <ToastContainer />
        <AlertContainer />
      </body>
    </html>
  );
}
