import fs from 'fs';
import path from 'path';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import { Suspense } from 'react';

import AlertContainer from '@/components/Alert/AlertContainer';
import DialogContainer from '@/components/DialogManager/DialogContainer';
import MemoDrawerContainer from '@/components/MemoDrawer/MemoDrawerContainer';
import ToastContainer from '@/components/Toast/ToastContainer';
import ToastHandler from '@/components/Toast/ToastHandler';
import UserProvider from '@/components/UserProvider/UserProvider';

import { Providers } from './providers';

const pretendard = localFont({
  src: [
    {
      path: '../../public/fonts/Pretendard-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-pretendard',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const spriteSvg = fs.readFileSync(path.join(process.cwd(), 'public', 'sprite.svg'), 'utf-8');

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${pretendard.variable} antialiased`}>
        <div dangerouslySetInnerHTML={{ __html: spriteSvg }} style={{ display: 'none' }} aria-hidden='true' />
        <Providers>
          <UserProvider />
          {children}

          <div id='toast-root' />
          <div id='alert-root' />
          <div id='dialog-root' />
          <div id='memo-drawer-root' />
          <Suspense fallback={null}>
            <ToastHandler />
          </Suspense>
          <ToastContainer />
          <AlertContainer />
          <DialogContainer />
          <MemoDrawerContainer />
        </Providers>
      </body>
    </html>
  );
}
